algoritmo "semnome"
// Função :
// Autor :
// Data : 02/05/2022
// Seção de Declarações 
var
valor_reais:real
cotacao:real
valor_em_dolar:real
inicio
// Seção de Comandos
escreval("digite o valor da cotacao em reais")
leia (cotacao)
escreval("digite a quantia em reias para coverter em dolar")
leia (valor_reais)
valor_em_dolar<-valor_reais/cotacao
escreval ("a quantia do valor em dolar é",valor_em_dolar)

fimalgoritmo
