algoritmo "semnome"
// Função :
// Autor :
// Data : 07/11/2022
// Seção de Declarações 
var
n1: vetor [1..10]  de inteiro
n2: vetor [1..10]  de inteiro
soma: vetor [1..10]  de inteiro
contador,contadorr:inteiro
inicio
// Seção de Comandos
para contador de 1 ate 10 faca
n1[contador]<- randi(50)
escreva (n1[contador])
fimpara

escreval ()

para contador de 1 ate 10 faca
n2[contador]<- randi(50)
fimpara




fimalgoritmo
