algoritmo "semnome"
// Função :
// Autor :
// Data : 16/08/2022
// Seção de Declarações 
var
time:caracter


inicio
// Seção de Comandos 

escreval ("qual é o seu time?")
leia (time)

escolha time
caso "santos" , "corinthians" , "palmeiras" , "sao paulo"

escreval ("EIXO SP")


caso "botafogo" , "vasco" , "flamengo" , "fluminense"

escreval ("EIXO RJ")

fimescolha


fimalgoritmo
