algoritmo "semnome"
// Função :
// Autor :
// Data : 02/05/2022
// Seção de Declarações 
var

N1,N2,N3,N4,TOTAL:inteiro
inicio
// Seção de Comandos
escreval ("digite o valor de N1")
leia (N1)
escreval ("digite o valor de N2")
leia (N2)
 escreval("digite o valor de N3")
leia (N3)
escreval ("digite o valor de N4")
leia (N4)
N1<-N1* N1
N2<-N2* N2
N3<-N3* N3
N4<-N4* N4
TOTAL<-N1+N2+N3+N4
escreval ("a soma de todos os numeros é",TOTAL)

fimalgoritmo
