algoritmo "semnome"
// Função :
// Autor :
// Data : 21/11/2022
// Seção de Declarações 
var

numero:inteiro
procedimento par_impar(num: inteiro)
inicio
      se numero % 2 = 0 entao
         escreval("o numero", nume, " é PAR")
      senao
           escreval("o numero", num, " é IMPAR")
      fimse-



fimprocedimento
inicio

escreval ("digite um numero")
leia (numero)
par_impar(numero)


fimalgoritmo
