algoritmo "semnome"
// Função :
// Autor :
// Data : 02/08/2022
// Seção de Declarações 
var
numero:inteiro
resto:real

inicio
// Seção de Comandos 
//2) Peça para o usuário digitar um valor informe se ele é par ou ímpar

escreval ("digite um numero:")
leia (numero)

resto<- numero mod 2

se resto= 1 entao

escreval("o numero é impar")

senao

escreval ("o numero é par")

fimse


fimalgoritmo
