algoritmo "semnome"
// Função :
// Autor :
// Data : 13/09/2022
// Seção de Declarações 
var
soma,inicial,final,contador:inteiro

inicio
// Seção de Comandos 
escreval ("qual é o numero inicial:")
leia (inicial)
escreval ("qual é o numero final:")
leia (final)

soma <- inicial + 0
escreval (soma)
para contador de inicial ate final - 1 faca

soma<- soma +1

escreval (soma)

fimpara



fimalgoritmo
