algoritmo "semnome"
// Função :
// Autor :
// Data : 12/09/2022
// Seção de Declarações 
var
contador:inteiro
nota1,nota2,soma,media:real
inicio
// Seção de Comandos 

para contador de 1 ate 3 faca

escreval ("aluno n " , contador)
escreval ("escreva nota 1 ")
leia(nota1)
escreval ("escreva nota 2 ")
leia(nota2)
soma<- nota1 + nota2
media<- soma / 2
escreval ("a media do aluno", contador, "é :", media)

fimpara





fimalgoritmo
