algoritmo "semnome"
// Função :
// Autor :
// Data : 13/09/2022
// Seção de Declarações 
var
altura,media,soma:real
contador:inteiro
n:inteiro
inicio
// Seção de Comandos 

n<- 0
para contador de 1 ate 6 faca
n<- n+1
escreval (" qual é a altura do integrante ", n , "?" )
leia (altura)

soma<- soma + altura

fimpara

media <- soma/6

escreval ("a media de altira do time é ", media)




fimalgoritmo
